### ISSUE TITLE
 java.lang.AssertionError

### ISSUE THREAD

**Issue by CrazyBoy49z** [olivernybroe/collector-intellij#132]
```
CompositeException (2 nested):
------------------------------
[1]: java.lang.AssertionError
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:820)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:848)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:848)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:773)
	at com.intellij.psi.impl.source.tree.injected.InjectedFileViewProvider.rootChangedImpl(InjectedFileViewProvider.java:33)
	at com.intellij.psi.impl.source.tree.injected.MultipleRootsInjectedFileViewProvider.rootChanged(MultipleRootsInjectedFileViewProvider.java:57)
	at com.intellij.psi.impl.source.PsiFileImpl.subtreeChanged(PsiFileImpl.java:364)
	at com.jetbrains.php.lang.psi.PhpFileImpl.subtreeChanged(PhpFileImpl.java:239)
	at com.intellij.psi.impl.source.tree.CompositeElement.subtreeChanged(CompositeElement.java:77)
	at com.intellij.psi.impl.source.tree.TreeElement.invalidate(TreeElement.java:338)
	at com.intellij.psi.impl.source.tree.TreeElement.rawRemove(TreeElement.java:325)
	at com.intellij.psi.impl.source.tree.TreeElement.rawReplaceWithList(TreeElement.java:332)
	at com.intellij.psi.impl.source.tree.CompositeElement.replace(CompositeElement.java:823)
	at com.intellij.psi.impl.source.tree.CompositeElement.lambda$replaceChild$1(CompositeElement.java:626)
	at com.intellij.psi.impl.source.tree.ChangeUtil$1.runInner(ChangeUtil.java:147)
	at com.intellij.pom.impl.PomTransactionBase.run(PomTransactionBase.java:28)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$1(PomModelImpl.java:111)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:222)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:625)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:162)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.replaceChildInternal(ASTDelegatePsiElement.java:385)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.replace(ASTDelegatePsiElement.java:375)
	at dev.nybroe.collector.quickFixes.ForeachToCollectionQuickFix.applyFix(ForeachToCollectionQuickFix.kt:52)
	at dev.nybroe.collector.quickFixes.ForeachToCollectionQuickFix.applyFix(ForeachToCollectionQuickFix.kt:14)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:75)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:224)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:147)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:224)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$5(ShowIntentionActionsHandler.java:257)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1003)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1029)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:257)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$4(ShowIntentionActionsHandler.java:233)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:232)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.chooseActionAndInvoke(IntentionListStep.java:135)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$3(IntentionListStep.java:127)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1538)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:179)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:172)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1535)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:219)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:207)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:266)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:434)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:406)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:356)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:269)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:354)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:109)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:710)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

[2]: java.lang.AssertionError
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:820)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:848)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:848)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:805)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.calculateMinEditSequence(DocumentWindowImpl.java:773)
	at com.intellij.psi.impl.source.tree.injected.InjectedFileViewProvider.rootChangedImpl(InjectedFileViewProvider.java:33)
	at com.intellij.psi.impl.source.tree.injected.MultipleRootsInjectedFileViewProvider.rootChanged(MultipleRootsInjectedFileViewProvider.java:57)
	at com.intellij.psi.impl.source.PsiFileImpl.subtreeChanged(PsiFileImpl.java:364)
	at com.intellij.psi.impl.source.tree.CompositeElement.subtreeChanged(CompositeElement.java:77)
	at com.intellij.psi.impl.source.tree.TreeElement.invalidate(TreeElement.java:338)
	at com.intellij.psi.impl.source.tree.TreeElement.rawRemove(TreeElement.java:325)
	at com.intellij.psi.impl.source.tree.TreeElement.rawReplaceWithList(TreeElement.java:332)
	at com.intellij.psi.impl.source.tree.TreeElement.applyReplaceOnReparse(TreeElement.java:234)
	at com.intellij.psi.impl.DiffLog$ReplaceEntry.doActualPsiChange(DiffLog.java:108)
	at com.intellij.psi.impl.DiffLog.performActualPsiChange(DiffLog.java:45)
	at com.intellij.pom.core.impl.PomModelImpl$1.runInner(PomModelImpl.java:246)
	at com.intellij.pom.impl.PomTransactionBase.run(PomTransactionBase.java:28)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$1(PomModelImpl.java:111)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:222)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$reparseFile$3(PomModelImpl.java:243)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$4(CodeStyleManagerImpl.java:459)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:128)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:487)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:458)
	at com.intellij.pom.core.impl.PomModelImpl.reparseParallelTrees(PomModelImpl.java:223)
	at com.intellij.pom.core.impl.PomModelImpl.commitTransaction(PomModelImpl.java:191)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$1(PomModelImpl.java:152)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:222)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:625)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:162)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.replaceChildInternal(ASTDelegatePsiElement.java:385)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.replace(ASTDelegatePsiElement.java:375)
	at dev.nybroe.collector.quickFixes.ForeachToCollectionQuickFix.applyFix(ForeachToCollectionQuickFix.kt:52)
	at dev.nybroe.collector.quickFixes.ForeachToCollectionQuickFix.applyFix(ForeachToCollectionQuickFix.kt:14)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:75)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:224)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:147)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:224)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$5(ShowIntentionActionsHandler.java:257)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1003)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1029)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:257)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$4(ShowIntentionActionsHandler.java:233)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:232)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.chooseActionAndInvoke(IntentionListStep.java:135)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$3(IntentionListStep.java:127)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1538)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:179)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:172)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1535)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:219)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:207)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:266)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:434)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:406)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:356)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:269)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:354)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:109)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:710)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

------------------------------

```

PhpStorm 2022.1.3
Build #PS-221.5921.28, built on June 22, 2022
Licensed to Yurij Finiv
Subscription is active until July 17, 2022.
Runtime version: 11.0.15+10-b2043.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 3048M
Cores: 8
Registry:
    ide.intellij.laf.enable.animation=true
    ide.windowSystem.autoShowProcessPopup=true
    run.processes.with.pty=TRUE
    editor.distraction.free.mode=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.2)
    pl.tigersoft.intellij.faker (1.2.0)
    net.sjrx.intellij.plugins.systemdunitfiles (0.3.8)
    lermitage.intellij.iconviewer (1.14.0.193)
    lermitage.intellij.extratci (1.21.0.201)
    io.aesy.regex101 (0.2)
    intellij.webp (221.5921.12)
    ideanginx9 (0.1.9)
    dev.meanmail.plugin.nginx-intellij-plugin (2021.3-2022.1)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.xiaobing1024.laravel (1.1.1)
    com.wakatime.intellij.plugin (14.0.6)
    com.ultrahob.zerolength.plugin2 (0.93)
    com.mintlify.document (1.1.6)
    com.materkey.codepoints (1.0.2)
    com.mallowigi.idea (18.1.0)
    com.intellij.properties (221.5921.15)
    com.wix.sasslint (1.1.2)
    com.github.czy211.licensetemplate (2.0.0)
    com.github.copilot (1.1.27.1718-nightly)
    com.github.chengpohi (1.9)
    cc.moky.intellij.plugin.svga-support (1.0.8)
    bundled-phpstorm-help (221.5921.28)
    com.intellij.jira (4.0.2)
    String Manipulation (9.5.0)
    LiveTemplatePreview (0.3)
    Key Promoter X (2022.2)
    zielu.gittoolbox (212.9.0)
    mobi.hsz.idea.gitignore (4.4.0)
    pers.fw.doc_en (1.1)
    nl.deschepers.laraveltinker (2.3.4)
    de.espend.idea.php.annotation (8.2.2)
    com.pestphp.pest-intellij (1.7.0)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    fr.adrienbrault.idea.symfony2plugin (2022.1.230)
    dev.nybroe.collector (0.4.0)
    com.boboram.laravelenvswitch (0.1.5)
    com.alicannklc.laravel.snippets (1.1.1)
    nz.hailwood.inertiajs (0.1.5)
    jones.restarteslintaction.restart-eslint-action (0.0.1)
    io.snyk.snyk-intellij-plugin (2.4.36)
    intellij.prettierJS (221.5921.12)
    com.mallowigi.colorHighlighter (11.0.0)
    com.laravel_idea.tailwind (1.3.2)
    org.i18nally.jetbrainsideplugin (1.4.1.2)
    izhangzhihao.rainbow.brackets (6.25)
    com.mallowigi (64.0.0)
    com.github.blarc.gitlab-template-lint-plugin (0.0.9)
    com.intellij.kubernetes (221.5921.12)
    ru.adelf.idea.dotenv (2022.1)
    com.laravel_idea.plugin (5.6.0.221)

**Comment by olivernybroe** [comment]
Hey 👋 

Sorry for never getting back to you on this issue. Issues like this are usually caused by a bug in phpstorm. Are you still experiencing this problem, if you are still using the plugin :) 

Will reopen, if this still happens and then I'll try and get in touch with phpstorm team.
