### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by CrazyBoy49z** [olivernybroe/collector-intellij#138]
```
Outdated stub in index: file:///.../vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php indexing timestamp = 1658842200000, binary = false, byte size = 28402, char size = 28311, doc=null, docSaved=true, wasIndexedAlready=true, queried at 1658842200000
doc length=-1
file length=28402
cached PSI class com.jetbrains.php.lang.psi.PhpFileImpl
PSI length=28402
projects with file: 1
physical file exists; length = 28402

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:634)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:255)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:85)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1790)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:85)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:65)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:138)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:185)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
	at com.jetbrains.php.PhpIndexImpl.getElements(PhpIndexImpl.java:658)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:1110)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:1085)
	at com.jetbrains.php.PhpIndexImpl.getByFqnCacheAware(PhpIndexImpl.java:1171)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:1165)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:1210)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.findSuper(PhpType.java:909)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.findSuper(PhpType.java:887)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.isConvertibleFrom(PhpType.java:803)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.isConvertibleFrom(PhpType.java:740)
	at dev.nybroe.collector.UtilKt.isCollection(Util.kt:52)
	at dev.nybroe.collector.UtilKt.isCollectionMethod(Util.kt:31)
	at dev.nybroe.collector.UtilKt.isCollectionMethod(Util.kt:34)
	at dev.nybroe.collector.inspections.WhereFirstInspection$buildVisitor$1.visitPhpMethodReference(WhereFirstInspection.kt:18)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:44)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:317)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:325)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:331)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:294)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:294)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:297)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at `com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)`
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:282)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:270)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

```
PhpStorm 2022.2.1
Build #PS-222.3739.61, built on August 18, 2022
Licensed to Yurij Finiv
Subscription is active until September 17, 2022.
Runtime version: 17.0.3+7-b469.37 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3048M
Cores: 8
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    ide.windowSystem.autoShowProcessPopup=true
    run.processes.with.pty=TRUE
    editor.distraction.free.mode=true
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.3)
    lermitage.intellij.iconviewer (1.15.0.193)
    lermitage.intellij.extratci (1.23.0.201)
    krasa.CpuUsageIndicator (1.14)
    io.aesy.regex101 (0.2)
    intellij.webp (222.3739.16)
    ideanginx9 (0.1.9)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.xiaobing1024.laravel (1.1.1)
    com.wakatime.intellij.plugin (14.1.0)
    com.villains.intelij.plugin.trashpandatheme (2.0.0)
    com.tabnine.TabNine (0.7.23)
    com.mroche.JsonHelper (1.2.0)
    com.mintlify.document (1.1.6)
    com.materkey.codepoints (1.0.2)
    com.mallowigi.idea (18.1.0)
    com.intellij.properties (222.3739.16)
    com.wix.sasslint (1.1.2)
    com.github.plaskowski.embeddedbrowserintellijplugin (1.2.0)
    com.github.czy211.licensetemplate (2.0.0)
    com.github.chengpohi (1.9.5)
    com.gerry.redis (2.5)
    com.flreey.codekits (2022.09.1)
    cc.moky.intellij.plugin.svga-support (1.0.8)
    cat.dcat.jbplug.mactabbing (1.1.0)
    bundled-phpstorm-help (222.3739.61)
    com.intellij.jira (4.2.0)
    String Manipulation (9.5.1)
    MultiHighlight (3.0.0)
    LiveTemplatePreview (0.3)
    Key Promoter X (2022.2)
    com.chuntung.plugin.gistsnippet (1.1.0)
    zielu.gittoolbox (212.9.9)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (72.0.0)
    pers.fw.doc_en (1.1)
    nl.deschepers.laraveltinker (2.4.0)
    de.espend.idea.php.annotation (8.2.3)
    com.pestphp.pest-intellij (1.8.1)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    dev.nybroe.collector (0.4.0)
    com.funivan.idea.phpClean (2022.08.30)
    com.alicannklc.laravel.snippets (1.1.1)
    jones.restarteslintaction.restart-eslint-action (0.0.1)
    intellij.prettierJS (222.3739.24)
    izhangzhihao.rainbow.brackets (6.25)
    dev.ekvedaras.laravelquery (3.3.0)
    org.i18nally.jetbrainsideplugin (1.4.1.3)
    io.snyk.snyk-intellij-plugin (2.4.43)
    fr.adrienbrault.idea.symfony2plugin (2022.1.234)
    com.mallowigi.colorHighlighter (12.0.0)
    com.github.blarc.gitlab-template-lint-plugin (0.0.12)
    com.intellij.kubernetes (222.3739.24)
    ru.adelf.idea.dotenv (2022.2)
    com.laravel_idea.plugin (5.8.1.222)
```

**Comment by olivernybroe** [comment]
Hey 👋 

Sorry for never getting back to you on this issue. Issues like this are usually caused by a bug in phpstorm. Are you still experiencing this problem, if you are still using the plugin :) 

Will reopen, if this still happens and then I'll try and get in touch with phpstorm team.
