### ISSUE TITLE
com.intellij.diagnostic.PluginException: Tool #ForeachToCollectionInspection registers INFORMATION level problem in batch mode

### ISSUE THREAD

**Issue by allanlaal** [olivernybroe/collector-intellij#83]
IntelliJ IDEA Ultimate 2021.2.2
  
	  com.intellij.diagnostic.PluginException: Tool #ForeachToCollectionInspection registers INFORMATION level problem in batch mode on PHP file. INFORMATION level 'warnings' are invisible in the editor and should not become visible in batch mode. Moreover, cause INFORMATION level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations [Plugin: dev.nybroe.collector]
		at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doInspectInBatch(LocalInspectionsPass.java:154)
		at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.inspectFile(GlobalInspectionContextImpl.java:475)
		at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runTools$4(GlobalInspectionContextImpl.java:338)
		at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:112)
		at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
		at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
		at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
		at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
		at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:112)
		at com.intellij.openapi.project.DumbService.tryRunReadActionInSmartMode(DumbService.java:129)
		at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runTools$10(GlobalInspectionContextImpl.java:327)
		at com.intellij.concurrency.JobLauncherImpl$1MyTask.lambda$call$0(JobLauncherImpl.java:293)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
		at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:280)
		at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:270)
		at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by allanlaal** [comment]
com.intellij.diagnostic.PluginException: Tool #ArrayMapToCollectionInspection registers INFORMATION level problem in batch mode on PHP file. INFORMATION level 'warnings' are invisible in the editor and should not become visible in batch mode. Moreover, cause INFORMATION level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations [Plugin: dev.nybroe.collector]
		at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doInspectInBatch(LocalInspectionsPass.java:154)
		at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.inspectFile(GlobalInspectionContextImpl.java:475)
		at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runTools$4(GlobalInspectionContextImpl.java:338)
		at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:112)
		at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
		at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
		at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
		at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
		at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:112)
		at com.intellij.openapi.project.DumbService.tryRunReadActionInSmartMode(DumbService.java:129)
		at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runTools$10(GlobalInspectionContextImpl.java:327)
		at com.intellij.concurrency.JobLauncherImpl$1MyTask.lambda$call$0(JobLauncherImpl.java:293)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
		at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:280)
		at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:270)
		at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by olivernybroe** [comment]
Thanks for reporting this. 

Did not know about this limitation when using batch mode. Just to verify, this happens when you run the inspection on multiple files at once right?

**Comment by allanlaal** [comment]
no, I got these when doing sth nonrelated to this plugin. it was just running in the background in a PHP project

**Comment by olivernybroe** [comment]
Hmm interesting, I'll see how I can solve them 👍

**Comment by rk** [comment]
I just experienced this exception when opening a project. I'm not sure how related it is to the original, but I didn't want to open a duplicate ticket.

```
com.intellij.diagnostic.PluginException: Tool #ArrayMapToCollectionInspection (class dev.nybroe.collector.inspections.ArrayMapToCollectionInspection) registers 'INFORMATION'-level problem in batch mode on PHP file. Warnings of the 'INFORMATION' level are invisible in the editor and should not become visible in batch mode. Moreover, since 'INFORMATION'-level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations [Plugin: dev.nybroe.collector]
	at com.intellij.codeInspection.InspectionEngine.warnAboutInformationLevelInBatchMode(InspectionEngine.java:267)
	at com.intellij.codeInspection.InspectionEngine$2.registerProblem(InspectionEngine.java:300)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:55)
	at dev.nybroe.collector.inspections.ArrayMapToCollectionInspection$buildVisitor$1.visitPhpFunctionCall(ArrayMapToCollectionInspection.kt:21)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl.accept(FunctionReferenceImpl.java:48)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:26)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:99)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:58)
	at com.intellij.codeInspection.InspectionEngine.lambda$inspectElements$8(InspectionEngine.java:317)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:89)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by olivernybroe** [comment]
@rk Thank you for reporting! It seems related, I'll def. have to take a closer look on this to understand the issue.

**Comment by olivernybroe** [comment]
Sorry for the veeeerry long wait on this 😆 

But this should have been fixed now and will be out in next release (2-3 days)
